main: pl.plajer.buildbattle.Main
version: 3.0.0-ALPHA
name: BuildBattle
depend: [WorldEdit]
softdepend: [BarAPI, Vault]
commands:
  leave:
    usage: /leave
    description: Leave the game
  buildbattle:
    usage: /buildbattle
    description: The main command
    aliases: [buildb, bb]
  addsigns:
    usage: /addsigns
    description: Adds signs to the plugin!
  stats:
    usage: /stats
    description: See your stats