main: pl.plajer.buildbattle.Main
version: 3.0.0-BETA
name: BuildBattle
depend: [WorldEdit]
softdepend: [BossBarAPI, Vault, PlaceholderAPI]
authors: [Plajer, TomTheDeveloper]

commands:
  buildbattle:
    usage: /buildbattle
    description: The main command
    aliases: [buildb, bb]

permissions:
  buildbattle.admin.*:
    default: op
    children:
      buildbattle.updatenotify: true
      buildbattle.admin.command: true
      buildbattle.admin.commands.override: true
      buildbattle.admin.sign.create: true