main: pl.plajer.buildbattle.Main
version: 3.0.0-ALPHA
name: BuildBattle
depend: [WorldEdit]
softdepend: [BarAPI, Vault, PlaceholderAPI]
authors: [Plajer, TomTheDeveloper]

commands:
  buildbattle:
    usage: /buildbattle
    description: The main command
    aliases: [buildb, bb]
  addsigns:
    usage: /addsigns
    description: Adds signs to the plugin!

permissions:
  buildbattle.admin.*:
    children:
      buildbattle.updatenotify: true
      buildbattle.