main: pl.plajer.buildbattle3.Main
version: 3.0.0 Beta 4
name: BuildBattle
depend: [WorldEdit]
softdepend: [BossBarAPI, Vault, PlaceholderAPI, Citizens]
authors: [Plajer, TomTheDeveloper]

commands:
  buildbattle:
    usage: /buildbattle
    description: The main command
    aliases: [buildb, bb]
  buildbattleadmin:
    aliases: [buildba, bba]

permissions:
  buildbattle.admin.*:
    default: op
    children:
      buildbattle.updatenotify: true
      buildbattle.admin: true
      buildbattle.admin.sign.create: true
      buildbattle.admin.sign.break: true